apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: social-media-analysis-mongo
  name: social-media-analysis-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: social-media-analysis-mongo
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: social-media-analysis-mongo
    spec:
      containers:
      - image: beaware/social-media-analysis-mongo
        imagePullPolicy: Always
        name: social-media-analysis-mongo
        ports:
        - containerPort: 27017
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 256Mi
