apiVersion: v1
kind: Service
metadata:
  labels:
    app: social-media-analysis-mongo
  name: social-media-analysis-mongo
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 27017
